export const MAX_CHECK_IN_DISTANCE_IN_KILOMETERS = 0.1
export const MAX_NEARBY_GYM_DISTANCE_IN_KILOMETERS = 10
export const CHECK_IN_VALIDATION_WINDOW_IN_MINUTES = 20
export const DEFAULT_PAGE_SIZE = 20
